name: Build and Push Docker Image to DockerHub

on:
  push:
    branches:
      - "**" # This triggers on every push to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build the Docker image
        run: docker build -t surajkumar00/flashfathom-ai .

      - name: Push the Docker image to DockerHub
        run: docker push surajkumar00/flashfathom-ai
